### PR TITLE
(more accurate?) relax spinner

### PR DESCRIPTION
**Pull request by Hazuki-san**
based on this line of code
```
if (velocityTheoretical > velocityCurrent)
	velocityCurrent += Math.Min(velocityTheoretical - velocityCurrent, velocityCurrent < 0 && Player.Relaxing ? maxAccelThisFrame / RELAX_BONUS_ACCEL : maxAccelThisFrame);
else
	velocityCurrent += Math.Max(velocityTheoretical - velocityCurrent, velocityCurrent > 0 && Player.Relaxing ? -maxAccelThisFrame / RELAX_BONUS_ACCEL : -maxAccelThisFrame);
```

### CODE REVIEW

**Comment by uyitroa** [comment]
Can you provide the source?

**Comment by Hazuki-san** [comment]
@uyitroa https://ghostbin.co/paste/ofgux

**Comment by Hazuki-san** [comment]
Sorry, I edited wrong line ... LOL

**Comment by uyitroa** [comment]
Where did you get the source code though, because as far as I know osu! stable isn't open source.

**Comment by uyitroa** [comment]
Anyway I'll need to figure out how to make a correct rpm meter first lol. Because the one I'm using is wrong.

**Comment by Hazuki-san** [comment]
If you need some game related code, I'll try to find it for you. If you got Discord `Aoba Suzukaze#0900` is my Discord :p

**Comment by uyitroa** [comment]
You disabled friend requests from everyone. Try adding me instead: uyitroa#3392

**Pull request closed without merging**
